<?php

namespace Tperroin\BasketBundle\Entity\User;

use Doctrine\ORM\EntityRepository;

/**
 * LicencieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencieRepository extends EntityRepository
{
    public function getLicenciesForSignUp()
    {

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder('l')
            ->select("l.id, CONCAT(l.firstname,' ',l.lastname)  as name")
            ->from('TperroinBasketBundle:User\Licencie', 'l');

        $query = $qb->getQuery();

        return $query->getResult();

    }

    public function getLicencieFromConcat($value)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder('l')
            ->select("l.id, l.firstname, l.lastname, CONCAT(l.firstname,' ',l.lastname)  as name")
            ->from('TperroinBasketBundle:User\Licencie', 'l')
            ->where("CONCAT(l.firstname,' ',l.lastname) = :value")
            ->setParameter('value', $value);

        $query = $qb->getQuery();

        return $query->getResult();

    }
}
