tperroin_utilities:
    resource: "@TperroinUtilitiesBundle/Controller/"
    type:     annotation
    prefix:   /

tperroin_basket:
    resource: "@TperroinBasketBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

news:
    type: rest
    resource: Tperroin\BasketBundle\Controller\NewsRestController
    prefix: api/trully/v1.0/news/
    options:
        expose: true

users:
    type: rest
    resource: Tperroin\BasketBundle\Controller\AuthorizationController
    prefix: api/trully/v1.0/users/
    options:
        expose: true

eventget:
    type: rest
    resource: Tperroin\BasketBundle\Controller\Events\EventGet
    prefix: api/trully/v1.0/events/
    options:
        expose: true

event:
    type: rest
    resource: Tperroin\BasketBundle\Controller\Events\Event
    prefix: api/fully/v1.0/events/
    options:
        expose: true

licencies:
    type: rest
    resource: Tperroin\BasketBundle\Controller\User\LicencieController
    prefix: api/trully/v1.0/users/licencies
    options:
        expose: true

api_login_check:
   path: /api/login_check

