security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
            dev:
                pattern:  ^/api/(_(profiler|wdt|doc))/
                security: false
            login:
                pattern:  ^/api/login
                stateless: true
                anonymous: true
                form_login:
                    check_path: /api/login_check
                    require_previous_session: false
                    username_parameter: username
                    password_parameter: password
                    success_handler: lexik_jwt_authentication.handler.authentication_success
                    failure_handler: lexik_jwt_authentication.handler.authentication_failure

            api:
                pattern:   ^/api/fully
                stateless: true
                lexik_jwt:
                    authorization_header:
                        enabled: true
                        prefix:  Bearer
                    query_parameter:
                        enabled: true
                        name:    bearer

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
